MIPS: Alchemy: pci: fix build: missing module.h
pci-alchemy.c:487:12: error: 'THIS_MODULE' undeclared here [...]

Signed-off-by: Manuel Lauss <manuel.lauss@googlemail.com>
To: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/2921/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>